
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
    max-http-form-post-size: 80KB
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop-online?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接时间，毫秒
      minimum-idle: 5           #最小连接数
      maximum-pool-size: 20     #最大连接数
      auto-commit: true         #自动提交
      idle-timeout: 600000      #连接超时时间
      pool-name: DateSourceHikaruCP #连接池名字
      max-lifetime: 1800000         #连接池生命时长
      connection-test-query: select 1 #测试语句
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 192.168.50.40
    port: 6379
  session:
    store-type: redis


mybatis:
  type-aliases-package: com.leiming.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  mappers: com.leiming.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
# 分页插件配置pagehelper
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
